/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdCopiesRouteImport } from './routes/ad-copies'
import { Route as IndexRouteImport } from './routes/index'

const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdCopiesRoute = AdCopiesRouteImport.update({
  id: '/ad-copies',
  path: '/ad-copies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ad-copies': typeof AdCopiesRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/generator': typeof GeneratorRoute
  '/overview': typeof OverviewRoute
  '/segments': typeof SegmentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ad-copies': typeof AdCopiesRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/generator': typeof GeneratorRoute
  '/overview': typeof OverviewRoute
  '/segments': typeof SegmentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ad-copies': typeof AdCopiesRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/generator': typeof GeneratorRoute
  '/overview': typeof OverviewRoute
  '/segments': typeof SegmentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ad-copies'
    | '/analytics'
    | '/campaigns'
    | '/generator'
    | '/overview'
    | '/segments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ad-copies'
    | '/analytics'
    | '/campaigns'
    | '/generator'
    | '/overview'
    | '/segments'
  id:
    | '__root__'
    | '/'
    | '/ad-copies'
    | '/analytics'
    | '/campaigns'
    | '/generator'
    | '/overview'
    | '/segments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdCopiesRoute: typeof AdCopiesRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRoute
  GeneratorRoute: typeof GeneratorRoute
  OverviewRoute: typeof OverviewRoute
  SegmentsRoute: typeof SegmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-copies': {
      id: '/ad-copies'
      path: '/ad-copies'
      fullPath: '/ad-copies'
      preLoaderRoute: typeof AdCopiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdCopiesRoute: AdCopiesRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRoute,
  GeneratorRoute: GeneratorRoute,
  OverviewRoute: OverviewRoute,
  SegmentsRoute: SegmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
